### ISSUE TITLE
Already progressed challenges are sometimes displayed at 0-1/xxx when filtering In Progress and but shows correctly when ticking Completed

### ISSUE THREAD

**Issue by Numiz** [theoarav/Payday3ChallengeViewer#1]
As the title specifies there seems to be some discrepancies with the filtering, I don't know if this is due to their terrible API or just an issue displaying. 

Example: KU59 Hip fire III 

![In Progress & Completed filtered](https://github.com/theoarav/Payday3ChallengeViewer/assets/4493024/f6dc875e-ed61-4f0d-918a-50a7f078af08)
![In Progress filtered](https://github.com/theoarav/Payday3ChallengeViewer/assets/4493024/8b4f80eb-1475-4b7c-898e-10c6cc80840f)

Please let me know if you need any additional data

**Comment by theoarav** [comment]
It's their API, I've got a lot of challenges myself tagged as In Progress when I have 1/1
For example in their API result I've got more than 15000 meters slided and my 5000 challenges is still marked as In progress and the next one is completed...
I don't really want to fix the JSON returned by the API ^^

**Comment by Numiz** [comment]
Yikes... Nebula has really screwed them over, I appreciate your work though!
