### ISSUE TITLE
Blank screen when clicking "show prerequisites"

### ISSUE THREAD

**Issue by zhexirox** [theoarav/Payday3ChallengeViewer#4]
When I click on the "show prerequisites" button of any challenge I get a blank screen and I have to close and reopen it to continue using it. It happens to me in both English and Spanish language. I use Windows 11 in case it has something to do with it.

Greetings.
![Screenshot_1](https://github.com/theoarav/Payday3ChallengeViewer/assets/7556630/ad92f91e-f4a8-416f-a7b3-c60121963fc5)
![Screenshot_2](https://github.com/theoarav/Payday3ChallengeViewer/assets/7556630/3bb8c700-9c64-4524-a7a6-6e34efe2e3c8)

**Comment by DudiVok** [comment]
Thank you for reporting the bug. Its actually happening because for whatever reason theres several "undefined" variables inside Payday localization files under some languages and when you open this page it does not have a fallback for that. This issue should be resolved in the upcoming release.
