### ISSUE TITLE
`getUserChallenges` does not check `accessTokenExp`

### ISSUE THREAD

**Issue by Nothing4You** [theoarav/Payday3ChallengeViewer#8]
https://github.com/theoarav/Payday3ChallengeViewer/blob/548cfcbfb39ac04385b8be2a28e9a7cc9f006062/src/renderer/src/service/auth.service.ts#L93-L117

this code only takes the stored access token but once it expires it just silently (to the user) fails, as the API starts returning 401.

this is probably also affecting the other API calls, but this is the first one it errors on.

the simplest workaround appears to be restarting the application.

**Comment by DudiVok** [comment]
Thank you for reporting the issue. We will take a look at it and try to fix it in the next release.

**Comment by DudiVok** [comment]
This issue will be fixed with the next release (v1.1.8)
